<a href="https://colab.research.google.com/github/Xeyah0214/Linear-Algebra-2nd-Sem/blob/main/Assignment_3_Matrix_in_Python_BERNARDO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
## Laboratory 2 : Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

#Objectives
At the end of this activity, you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matric operations
3. Program and transate matrix equations and operations using Python.

#Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##Matrices
A matrix is defined as a rectangular array of numbers, symbols, or expressions that are arranged in rows and columns inside a bracket. It is commonly used in programming to store or display data in a structured format. By storing values in a matrix, a program can access and perform operations on the data more efficiently. 

Let's say for example you have A and B as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\ 
        3w-x -2y +z \\
        2w-x + 3y -2z
    \end{array}
\right. $$

We could see that A is a system of 2 equations with 2 parameters. While B isa a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1\\ 2 & -1 & 3 & -2\end{bmatrix}
$$


Just like our previous laboratory activity, we'll represent system of lienar equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structures of matrices. And just like arrays, these elements are indezed according their position with respect to their rows and columns. This can be represented just like the equation below. Whereas A is a matrix consisting of elements denoted by aij. Denoted by i is the number of rows in the matrix while j stands for the numner of columns.
Do note that the size of a matrix is i x j.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors byt we'll further discuss them in this laboratory activity.

In [ ]:
##Since we'll keep on describing matrices, Let's make a function. 
def describe_mat(matrix):
  print (f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
##Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
##Declaring a 3 x 2 matrix
M = np.array([
    [6, 2],
    [1, 4],
    [5, 7]
])
describe_mat(M)
     

Matrix:
[[6 2]
 [1 4]
 [5 7]]

Shape:	(3, 2)
Rank:	2



#Categorizing Matrices
Matrices come in a variety of shapes and elemental values due to the diverse arrangements of values inside its elements and dimensions. With this, they can be divided into the following categories:

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    26, 4, 19
]) ## this is a 1-D Matrix with a shape of (1, 3), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [11 ,23 ,64, -9]
]) ## this is a 2-D Matrix with a shape of (1, 4)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[26  4 19]

Shape:	(3,)
Rank:	1

Matrix:
[[11 23 64 -9]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [14],
    [12],
    [25]
]) ##this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[14]
 [12]
 [25]]

Shape:	(3, 1)
Rank:	2



###Square Matrices
Square matrices are defined with the same number of rows and columns. If i = j, we can say that a matrix is square. To find square matrices, we can modify our matrix descriptor function.

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
  [12, 24, 15],
  [33, 17, 84],
  [60, 14, 21]
])
non_square_mat = np.array([
  [12, 24, 15],
  [33, 17, 84]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[12 24 15]
 [33 17 84]
 [60 14 21]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[12 24 15]
 [33 17 84]]

Shape:	(2, 3)
Rank:	2
Is Square: False



##According to element values

###Null Matrix
A Null Matrix is a matrix that has no elements. Its always a subspace of any vector or matrix

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


###Zero Matrix
In mathematics, particularly linear algebra and so as in Python programming, a zero matrix is a matrix all of whose entries are valued zero. 

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


###Ones Matrix
A matrix of ones or all-ones matrix is a matrix where every element is equal to one. Similarly to zero matrix; however, the element values would always be ones. 

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


###Diagonal Matrix
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
          [14,0,0],
          [0,30,0],
          [0,0,25]     
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[14,  0,  0],
       [ 0, 30,  0],
       [ 0,  0, 25]])

---shortcut below---

In [ ]:
d = np.diag([14,30,25,17])
d.shape[0] == d.shape[1]
d

array([[14,  0,  0,  0],
       [ 0, 30,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 17]])

###Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(4)



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

##Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
   [1,8,2,9],
   [0,3,1,-2],
   [0,0,13,2],
   [0,0,0,18]       
])

array([[ 1,  8,  2,  9],
       [ 0,  3,  1, -2],
       [ 0,  0, 13,  2],
       [ 0,  0,  0, 18]])

##Lower Triangular Matrix
This is the opposite of upper triangular where there is no values above the diagonal.

In [ ]:
np.array([
    [19,0,0],
    [43,65,0],
    [86,18,25]
])

array([[19,  0,  0],
       [43, 65,  0],
       [86, 18, 25]])

#Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$


**Answer**

In [ ]:
num_1 = np.array([
    [5, 3, -1]
])
print (num_1)

[[ 5  3 -1]]


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


**Answer**

In [ ]:
num_2 = np.array([
    [1, 2, 1],
    [0, 4, -1],
    [0, 0, 10]  
])
describe_mat(num_2)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown.


In [ ]:
G = np.array([
    [1, 7, 8],
    [2, 2, 2],
    [4, 6, 7]
])

**Answer**

Linear Combination:
$$
G = \left\{
    \begin{array}\
        x_1+7x_2+8x_3 \\ 
        2x_1+2x_2+2x_3 \\
        4x_1+6x_2+7x_3
    \end{array}
\right. $$

LaTeX:
$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

**Answer**

Linear Combination:
$$
H = \left\{
    \begin{array}\
        x_1 \\ 
        2x_1+2x_2\\
        4x_1+6x_2+7x_3
    \end{array}
\right. $$

LaTeX:
$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}
$$

#Matrix Algebra

###Addition

In [ ]:
A = np.array([
    [4,6],
    [9,2],
    [9,3]
])
B = np.array([
    [7,8],
    [1,5],
    [2,6]
])
A+B

array([[11, 14],
       [10,  7],
       [11,  9]])

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 6,  8],
       [11,  4],
       [11,  5]])

###Subtraction

In [ ]:
A-B

array([[-3, -2],
       [ 8, -3],
       [ 7, -3]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

###Element-Wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

array([[28, 48],
       [ 9, 10],
       [18, 18]])

In [ ]:
2*A

array([[ 8, 12],
       [18,  4],
       [18,  6]])

#Activity

##Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

  1. Displays the shape, size, and rank of the matrix.
  2. Displays whether the matrix is square or non-square.
  3. Displays whether the matrix is an empty matrix.
  4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3). Create a flowchart discuss the functions and methods you have done. 
Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
#functions
import numpy as np

In [ ]:
# mat_desc functions and descriptions

def mat_desc(mat):
  sq = False
  mat = np.array(mat)
  print(mat)
  print('Shape', mat.shape)
  print('Size', mat.size)
  print('Rank', np.linalg.matrix_rank(mat))
  if(mat.shape[0] == mat.shape[1]):
    sq = True
    print('Square Matrix')
  else: 
    print('Non-Square Matrix')
  if(mat.shape[0] == 0 and mat.shape[1] == 0):
    print('Empty Matrix')
  else:
    print('Matrix is not empty')
  iden = np.identity(mat.shape[0])
  if(sq and (iden == mat).all()):
    print('Identity Matrix')
  else:
    print('Not an Identity Matrix')
  one = np.ones((mat.shape[0], mat.shape[1]))
  if(one == mat).all ():
    print('Ones Matrix')
  else:
    print('Not a Ones Matrix')
  zero = np.zeros((mat.shape[0], mat.shape[1]))
  if((zero == mat).all()):
    print('Zero Matrix')
  else:
    print('Non-Zero Matrix')

In [ ]:
print('Matrix A:')
mat_desc([
    [2, 14, 7],
    [1, 3, 8],
    [95, 32, 6],
    [19, 5, 17]
])

Matrix A:
[[ 2 14  7]
 [ 1  3  8]
 [95 32  6]
 [19  5 17]]
Shape (4, 3)
Size 12
Rank 3
Non-Square Matrix
Matrix is not empty
Not an Identity Matrix
Not a Ones Matrix
Non-Zero Matrix


In [ ]:
print('Matrix B:')
mat_desc([
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])


Matrix B:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape (5, 4)
Size 20
Rank 0
Non-Square Matrix
Matrix is not empty
Not an Identity Matrix
Not a Ones Matrix
Zero Matrix


In [ ]:
print('Matrix C:')
mat_desc([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1]
])

Matrix C:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape (5, 5)
Size 25
Rank 1
Square Matrix
Matrix is not empty
Not an Identity Matrix
Ones Matrix
Non-Zero Matrix


In [ ]:
print('Matrix D:')
mat_desc([
    [40, 32, 24, 3, 4, 0],
    [11, 8, 52, 25, 89, -2],
    [95, 16, 59, 4, 45, 9],
    [22, 46, 91, 1, -34, 77],
    [31, 36, 2, 96, 51, 95]
])


Matrix D:
[[ 40  32  24   3   4   0]
 [ 11   8  52  25  89  -2]
 [ 95  16  59   4  45   9]
 [ 22  46  91   1 -34  77]
 [ 31  36   2  96  51  95]]
Shape (5, 6)
Size 30
Rank 5
Non-Square Matrix
Matrix is not empty
Not an Identity Matrix
Not a Ones Matrix
Non-Zero Matrix


In [ ]:
print('Matrix E:')
mat_desc([
    [0,1,1,1,1],
    [1,1,0,1,1],
    [1,1,1,0,1],
    [1,1,1,1,0],
    [1,1,1,0,1],
    [1,1,1,1,1]
])

Matrix E:
[[0 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 0 1]
 [1 1 1 1 1]]
Shape (6, 5)
Size 30
Rank 5
Non-Square Matrix
Matrix is not empty
Not an Identity Matrix
Not a Ones Matrix
Non-Zero Matrix


##Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.
Returns the sum of the matrices.
Returns the difference of the matrices.
Returns the element-wise multiplication of the matrices.
Returns the element-wise division of the matrices.
Use 3 sample matrices in which their shapes are not lower than (3, 3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [2]:
# mat_operations function

def mat_operations(matrix):
  print(f'{matrix}')

In [3]:
##Creating Matrices
RF = int(input('Enter your desired number of rows:'))
CF = int(input('Enter your desired number of columns:'))
print('\nEnter',RF*CF, 'values for Matrix F\n\t(NOTE: Use space for separating the values entered)\n\t(NOTE: Your first ',CF,' number/s will be designated as the first row):')
mF = list(map(int, input().split()))
mat_F = np.array(mF).reshape(RF, CF)
print('\nMatrix F is:')
mat_operations(mat_F)

print ('------------------------------------------')

RG = int(input('Enter your desired number of rows:'))
CG = int(input('Enter your desired number of columns:'))
print('\nEnter',RG*CG, 'values for Matrix G\n\t(NOTE: Use space for separating the values entered)\n\t(NOTE: Your first ',CG,' number/s will be designated as the first row):')
mG = list(map(int, input().split()))
mat_G = np.array(mG).reshape(RG, CG)
print('\nMatrix G is:')
mat_operations(mat_G)

print ('------------------------------------------')

RH = int(input('Enter your desired number of rows:'))
CH = int(input('Enter your desired number of columns:'))
print('\nEnter',RH*CH, 'values for Matrix H\n\t(NOTE: Use space for separating the values entered)\n\t(NOTE: Your first ',CH,' number/s will be designated as the first row):')
mH = list(map(int, input().split()))
mat_H = np.array(mH).reshape(RH, CH)
print('\nMatrix H is:')
mat_operations(mat_H)

print ('------------------------------------------')

RI = int(input('Enter your desired number of rows:'))
CI = int(input('Enter your desired number of columns:'))
print('\nEnter',RI*CI, 'values for Matrix I\n\t(NOTE: Use space for separating the values entered)\n\t(NOTE: Your first ',CI,' number/s will be designated as the first row):')
mI = list(map(int, input().split()))
mat_I = np.array(mI).reshape(RI, CI)
print('\nMatrix I is:')
mat_operations(mat_I)


Enter your desired number of rows:3
Enter your desired number of columns:3

Enter 9 values for Matrix F
	(NOTE: Use space for separating the values entered)
	(NOTE: Your first  3  number/s will be designated as the first row):
1 -22 3 4 52 6 0 8 -19 

Matrix F is:
[[  1 -22   3]
 [  4  52   6]
 [  0   8 -19]]
------------------------------------------
Enter your desired number of rows:4
Enter your desired number of columns:4

Enter 16 values for Matrix G
	(NOTE: Use space for separating the values entered)
	(NOTE: Your first  4  number/s will be designated as the first row):
12 -3 44 76 -9 -8 -4 2 -13 7 -16 21 -5 18 34 51

Matrix G is:
[[ 12  -3  44  76]
 [ -9  -8  -4   2]
 [-13   7 -16  21]
 [ -5  18  34  51]]
------------------------------------------
Enter your desired number of rows:5
Enter your desired number of columns:4

Enter 20 values for Matrix H
	(NOTE: Use space for separating the values entered)
	(NOTE: Your first  4  number/s will be designated as the first row):
29 21 23

In [4]:
##Determination of the viability in operation of matrices
print('Matrix F:')
mat_operations(mat_F)
print('Matrix G:')
mat_operations(mat_G)
result1 = (mat_F.shape == mat_G.shape)
if result1:
  print('\nMatrix F and Matrix G are VIABLE for operation')
else:
  print('\nMatrix F and Matrix G are NOT VIABLE for operation')

print ('------------------------------------------')

print('Matrix G:')
mat_operations(mat_G)
print('Matrix H:')
mat_operations(mat_H)
result2 = (mat_G.shape == mat_H.shape)
if result2:
  print('\nMatrix G and Matrix H are VIABLE for operation')
else:
  print('\nMatrix G and Matrix H are NOT VIABLE for operation')

print ('------------------------------------------')

print('Matrix F:')
mat_operations(mat_F)
print('Matrix H:')
mat_operations(mat_H)
result3 = (mat_F.shape == mat_H.shape)
if result3:
  print('\nMatrix F and Matrix H are VIABLE for operation')
else:
  print('\nMatrix F and Matrix H are NOT VIABLE for operation')

print ('------------------------------------------')

print('Matrix G:')
mat_operations(mat_G)
print('Matrix I:')
mat_operations(mat_I)
result4 = (mat_G.shape == mat_I.shape)
if result4:
  print('\nMatrix G and Matrix I are VIABLE for operation')
else:
  print('\nMatrix G and Matrix I are NOT VIABLE for operation')

Matrix F:
[[  1 -22   3]
 [  4  52   6]
 [  0   8 -19]]
Matrix G:
[[ 12  -3  44  76]
 [ -9  -8  -4   2]
 [-13   7 -16  21]
 [ -5  18  34  51]]

Matrix F and Matrix G are NOT VIABLE for operation
------------------------------------------
Matrix G:
[[ 12  -3  44  76]
 [ -9  -8  -4   2]
 [-13   7 -16  21]
 [ -5  18  34  51]]
Matrix H:
[[ 29  21  23   3]
 [  4   6  10  87]
 [ -9  34  65  -1]
 [ 23   0  19  -6]
 [ 13  22  96 -21]]

Matrix G and Matrix H are NOT VIABLE for operation
------------------------------------------
Matrix F:
[[  1 -22   3]
 [  4  52   6]
 [  0   8 -19]]
Matrix H:
[[ 29  21  23   3]
 [  4   6  10  87]
 [ -9  34  65  -1]
 [ 23   0  19  -6]
 [ 13  22  96 -21]]

Matrix F and Matrix H are NOT VIABLE for operation
------------------------------------------
Matrix G:
[[ 12  -3  44  76]
 [ -9  -8  -4   2]
 [-13   7 -16  21]
 [ -5  18  34  51]]
Matrix I:
[[ 10  87  -9  34]
 [ 65  -1  22   3]
 [  4  13  22  96]
 [-21   0  12  -2]]

Matrix G and Matrix I are VIABLE for opera

In [5]:
##Sum of the Matrices

if result4:
  sum_1 = mat_G + mat_I
  print('Sum result 1:\n',sum_1)
else:
  print("Matrix G and Matrix I are not viable for sum operation")

print ('------------------------------------------')
if result1:
  sum_3 = mat_F + mat_G
  print('\n\nSum result 2:\n',sum_3)
else:
  print("Sum result 2: Matrix F and Matrix G are not viable for sum operation")

print ('------------------------------------------')

if result3:
  sum_2 = mat_F + mat_H
  print('\n\nSum result 2:\n',sum_2)
else:
  print("Sum result 3: Matrix F and Matrix H are not viable for sum operation")

print ('------------------------------------------')

Sum result 1:
 [[ 22  84  35 110]
 [ 56  -9  18   5]
 [ -9  20   6 117]
 [-26  18  46  49]]
------------------------------------------
Sum result 2: Matrix F and Matrix G are not viable for sum operation
------------------------------------------
Sum result 3: Matrix F and Matrix H are not viable for sum operation
------------------------------------------


In [6]:
##Difference of the Matrices
if result4:
  d_1 = mat_G - mat_I
  print('Difference result 1:\n',d_1)
else:
  print("Difference result 1: Matrix G and Matrix I are not viable for differece operation")

print ('------------------------------------------')
if result2:
  d_2 = mat_G - mat_H
  print('Difference result 2:\n',d_2)
else:
  print("Difference result 2: Matrix G and Matrix H are not viable for difference operation")

print ('------------------------------------------')

if result3:
  d_3 = mat_F - mat_H
  print('\Difference result 3:\n',d_2)
else:
  print("Difference result 3: Matrix F and Matrix H are not viable for difference operation")

print ('------------------------------------------')

Difference result 1:
 [[  2 -90  53  42]
 [-74  -7 -26  -1]
 [-17  -6 -38 -75]
 [ 16  18  22  53]]
------------------------------------------
Difference result 2: Matrix G and Matrix H are not viable for difference operation
------------------------------------------
Difference result 3: Matrix F and Matrix H are not viable for difference operation
------------------------------------------


In [7]:
##Element-Wise Multiplication of the Matrices
if result2:
  m_1 = mat_G * mat_H
  print('Product result 1:\n',m_1)
else:
  print("Product result 1: Matrix G and Matrix H are not viable for multiplication operation")

print ('------------------------------------------')

if result3:
  m_2 = mat_F * mat_H
  print('Product result 2:\n',m_2)
else:
  print("Product result 2: Matrix F and Matrix H are not viable for multiplication operation")

print ('------------------------------------------')

if result4:
  m_3 = mat_G * mat_I
  print('Product result 3:\n',m_3)
else:
  print("Product result 3: Matrix G and Matrix I are not viable for multiplication operation")

Product result 1: Matrix G and Matrix H are not viable for multiplication operation
------------------------------------------
Product result 2: Matrix F and Matrix H are not viable for multiplication operation
------------------------------------------
Product result 3:
 [[ 120 -261 -396 2584]
 [-585    8  -88    6]
 [ -52   91 -352 2016]
 [ 105    0  408 -102]]


In [8]:
##Element-Wise Division of the Matrices
if result1:
  dv_1 = mat_F * mat_G
  print('Quotient result 1:\n',dv_1)
else:
  print("Quotient result 1: Matrix F and Matrix G are not viable for division operation")

print ('------------------------------------------')

if result2:
  dv_2 = mat_G * mat_H
  print('Quotient result 2:\n',dv_2)
else:
  print("Quotient result 2: Matrix G and Matrix H are not viable for division operation")

print ('------------------------------------------')

if result3:
  dv_3 = mat_F * mat_H
  print('Quotient result 3:\n',dv_3)
else:
  print("Quotient result 3: Matrix F and Matrix H are not viable for division operation")


Quotient result 1: Matrix F and Matrix G are not viable for division operation
------------------------------------------
Quotient result 2: Matrix G and Matrix H are not viable for division operation
------------------------------------------
Quotient result 3: Matrix F and Matrix H are not viable for division operation
