<a href="https://colab.research.google.com/github/Xeyah0214/Linear-Algebra-2nd-Sem/blob/main/BERNARDO_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 6 : Matrix Operations


We'll try to do the same operations with matrices and even more now that you have a basic understanding of how to describe and operate with vectors and the principles of matrices.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

#Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


##Transposition
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for matrix A, its transpose is denoted as $A^T$. So for example:

:$$
A=\begin{bmatrix} 1 & 2 & 5 & \\ 5 & -1 & 0 & \\ 0 & 3 & 3 & \end{bmatrix}
$$


:$$
A^T=\begin{bmatrix} 1 & 5 & 0 & \\ 2 & -1 & -3 & \\ 5 & 0 & 3 & \end{bmatrix}
$$

In [ ]:
A = np.array([
    [11, 22, 55],
    [55, -11, 0],
    [0, -33, 33]
])


In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 11,  55,   0],
       [ 22, -11, -33],
       [ 55,   0,  33]])

In [ ]:
AT2 = A.T
AT2

array([[ 11,  55,   0],
       [ 22, -11, -33],
       [ 55,   0,  33]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1, 4, 2, 6],
    [7, 9, 3, -2],
    [5, -8, 0, 1]
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.shape

(4, 3)

Try to create your own matrix (you can try non-squares) to test transposition

In [ ]:
xeyah = np.array ([
                   [3, 14, 9, 5],
                   [4, 1,-8, 19],
                   [12, -3, 2, 1],
                   [5, 0, -18, 4],
                   [0, -61, 9, 7]
])
print('xeyah matrix: \n',xeyah, '\n')
print('Shape: ',xeyah.shape)

xeyah matrix: 
 [[  3  14   9   5]
 [  4   1  -8  19]
 [ 12  -3   2   1]
 [  5   0 -18   4]
 [  0 -61   9   7]] 

Shape:  (5, 4)


In [ ]:
xeyahT2 = xeyah.T
xeyahT2

array([[  3,   4,  12,   5,   0],
       [ 14,   1,  -3,   0, -61],
       [  9,  -8,   2, -18,   9],
       [  5,  19,   1,   4,   7]])

In [ ]:
print('Transpose Shape:',xeyah.shape)

Transpose Shape: (5, 4)


In [ ]:
print('Transpose Shape:',np.transpose(xeyah).shape)

Transpose Shape: (4, 5)


##Dot Product

If you remember the dot product from the laboratory activity, we'll try to do the same thing with matrices. We'll obtain the sum of products of the vectors by row-column pairings in matrix dot product. So, if we have two matrices $X$ and $Y$, we can do the following:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
C = np.array([
    [0, 2],
    [5, 3],
    [4, 0]
])
T = np.array([
    [-2, 8, 0, 3, 9, 4, -1],
    [0, -8, 5, 1, 1, 6, 7]
])

In [ ]:
np.array_equiv(C, T)

False

In [ ]:
np.dot(C,T)

array([[  0, -16,  10,   2,   2,  12,  14],
       [-10,  16,  15,  18,  48,  38,  16],
       [ -8,  32,   0,  12,  36,  16,  -4]])

In [ ]:
C.dot(T)

array([[  0, -16,  10,   2,   2,  12,  14],
       [-10,  16,  15,  18,  48,  38,  16],
       [ -8,  32,   0,  12,  36,  16,  -4]])

In [ ]:
C @ T

array([[  0, -16,  10,   2,   2,  12,  14],
       [-10,  16,  15,  18,  48,  38,  16],
       [ -8,  32,   0,  12,  36,  16,  -4]])

In [ ]:
np.matmul(C,T)

array([[  0, -16,  10,   2,   2,  12,  14],
       [-10,  16,  15,  18,  48,  38,  16],
       [ -8,  32,   0,  12,  36,  16,  -4]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### RULE 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$C = \begin{bmatrix}2&44\\21&-20\\0&11\end{bmatrix}, H = \begin{bmatrix}14&11\\3&-23\\-11&-32\end{bmatrix}, E = \begin{bmatrix}9&4&-3\\1&0&8\end{bmatrix}$$

So in this case $C$ has a shape of $(3,2)$, $H$ has a shape of $(3,2)$ and $E$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $C \cdot E$, or $H \cdot E$.  

In [ ]:
C = np.array([
    [2, 44, 1],
    [21, -20, 9],
    [0, 12, 11]
])
H = np.array([
    [14, 0, 11],
    [3,-23, 11],
    [-11, 24, -3],
    [2, 34, 6,]
])
E = np.array([
    [1, 9, 4, -3],
    [24, 1, 0, 8]
])
print(C.shape)
print(H.shape)
print(E.shape)

(3, 3)
(4, 3)
(2, 4)


In [ ]:
H @ C

array([[   28,   748,   135],
       [ -477,   724,   -83],
       [  482, -1000,   172],
       [  718,  -520,   374]])

In [ ]:
E @ H

array([[  -9, -213,   80],
       [ 355,  249,  323]])

In [ ]:
C @ H

ValueError: ignored

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
C @ H.T

array([[  39, -995, 1031, 1506],
       [ 393,  622, -738, -584],
       [ 121, -155,  255,  474]])

In [ ]:
X = np.array([
    [3,-1,3,4]
])
Y = np.array([
    [9,0,2,-8]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 27,  -9,  27,  36],
       [  0,   0,   0,   0],
       [  6,  -2,   6,   8],
       [-24,   8, -24, -32]])

In [ ]:
X @ Y.T

array([[1]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

###RULE 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [-23,0,21],
    [44,52,0],
    [1,34,97]
])
B = np.array([
    [-18,1,77],
    [14,-91,9],
    [-98,4,-18]
])
C = np.array([
    [9,-7,0],
    [10,0,1],
    [-31,0,66]
])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(np.eye(3))

array([[-23.,   0.,  21.],
       [ 44.,  52.,   0.],
       [  1.,  34.,  97.]])

In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
E = A @ (B @ C)
E

array([[  52433,   11508, -141773],
       [-166992,     448,  249808],
       [ -66229,   63336,  -92663]])

In [ ]:
F = (A @ B) @ C
F

array([[  52433,   11508, -141773],
       [-166992,     448,  249808],
       [ -66229,   63336,  -92663]])

In [ ]:
np.array_equal(E, X)

False

In [ ]:
np.array_equiv(E, F)

True

In [ ]:
A @ E

array([[ -2596768,   1065372,   1314856],
       [ -6376532,    529648,   6752004],
       [-12049508,   6170332,   -636612]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

###Determinants
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&8\\0&7\end{bmatrix}, |A| = 7$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [1,8],
    [0,7]
])
np.linalg.det(A)

6.999999999999999

In [ ]:
B = np.array([
              [1, 9, 3],
              [4, -1 ,-2],
              [0, -3, 2],
             
])
np.linalg.det(B)

-116.00000000000009

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

###Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}2&4\\-3&9\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (2)(9)-(-3)(4) = 30$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{30} \begin{bmatrix} 9 & -4 \\ 3 & 2\end{bmatrix} = \begin{bmatrix} \frac{9}{30} & \frac{-4}{30} \\ \frac{3}{30} & \frac{2}{30}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [2,4],
    [-3, 9]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [5, 10, 0],
              [8, 4, -2],
              [3, 6, 9]
])
Q = np.linalg.inv(P)
Q

array([[-8.88888889e-02,  1.66666667e-01,  3.70370370e-02],
       [ 1.44444444e-01, -8.33333333e-02, -1.85185185e-02],
       [-6.66666667e-02, -1.54197642e-18,  1.11111111e-01]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -2.77555756e-17,  0.00000000e+00],
       [ 2.77555756e-17,  1.00000000e+00,  0.00000000e+00],
       [-1.38777878e-17,  1.38777878e-17,  1.00000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the whether the matrices that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.5, 1.0, 1.5],
    [0.7, 0.9, 0.9],
    [0.3, 0.2, 2.0]
])
weights = np.array([
    [0.1, 0.2, 0.7]
])
p_grade = squad @ weights.T
p_grade


array([[1.4 ],
       [0.88],
       [1.47]])

##Activity

### Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
I = np.array([
    [5, 1, 44],
    [12, 63, 0],
    [45, 10, 1]          
])

J = np.array([
    [3, 22, 26],
    [2, 12, -16],
    [97, 4, -2]          
])

K = np.array([
    [29, -70, 4],
    [14, -6, 9],
    [29, 0, 37]          
])

In [ ]:
I @ J

array([[4285,  298,   26],
       [ 162, 1020, -696],
       [ 252, 1114, 1008]])

In [ ]:
J @ I

array([[1449, 1649,  158],
       [-566,  598,   72],
       [ 443,  329, 4266]])

In [ ]:
np.array_equiv(I @ J, J @ I)

False

In [ ]:
I @ (J@K)

array([[ 129191, -301738,   20784],
       [  -1206,  -17460,  -15924],
       [  52136,  -24324,   48330]])

In [ ]:
(I@J) @ K

array([[ 129191, -301738,   20784],
       [  -1206,  -17460,  -15924],
       [  52136,  -24324,   48330]])

In [ ]:
np.array_equiv(I@(J@K),(I@J)@K)

True

In [ ]:
I@(J+K)

array([[ 5720,   -58,  1683],
       [ 1392,  -198,   -81],
       [ 1726, -2096,  1315]])

In [ ]:
I@J + I@K

array([[ 5720,   -58,  1683],
       [ 1392,  -198,   -81],
       [ 1726, -2096,  1315]])

In [ ]:
np.array_equiv(I@(J+K),I@J + I@K)

True

In [ ]:
(J+K)@I

array([[  934, -2692,  1438],
       [ -163,   324,   697],
       [ 2253,   728,  5579]])

In [ ]:
J@I + K@I

array([[  934, -2692,  1438],
       [ -163,   324,   697],
       [ 2253,   728,  5579]])

In [ ]:
np.array_equiv((J+K)@I, J@I + K@I)

True

In [ ]:
I@np.eye(3)

array([[ 5.,  1., 44.],
       [12., 63.,  0.],
       [45., 10.,  1.]])

In [ ]:
np.array_equiv(I, I@np.eye(3))

True

In [ ]:
I@np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equiv(I@np.zeros((3,3)),np.zeros((3,3)))

True

In [ ]:
I.dot(np.zeros(I.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros (I.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
i_dot_z = I.dot(np.zeros(I.shape))
i_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(i_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(I.shape, dtype = float)
null = np.array(null_mat,dtype = float)
print(null)
np.allclose(i_dot_z , null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Conclusion
For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. 